name: strawberry
channels:
  - conda-forge
  - openalea
  - openalea/label/unstable
  
dependencies:
  - python=2.7
  - sphinx
  - nbsphinx
  - pandoc
  - numpy
  - ipython
  - sphinx_rtd_theme
  - openalea.plantgl
  - openalea.lpy 
  - boost=1.66
