name: strawberry
channels:
  - fredboudon
  - conda-forge
  - openalea

dependencies:
 - python=3.8  
 - openalea.deploy 
 - openalea.mtg 
 - openalea.plantgl 
 - pip:
   - pyvis
   - pandas
   - k3d
   - jupyter
   - voila
   - voila-vuetify
   - nodejs
   - cufflinks
   - ipyvuetify
   - plotly
   - nbsphinx
   - sphinx-rtd-theme
   - nbsphinx-link
