name: strawberry
channels:
  - conda-forge
  - openalea
  - openalea/label/unstable
  
dependencies:
  - python=2.7
  - openalea.strawberry
  - sphinx
  - nbsphinx
  - pandoc
  - numpy
  - ipython
  - sphinx_rtd_theme
